import Head from 'next/head'
// import Test from '../components/Test'
// import ScaleTest from '../components/ScaleTest'
// import DynamicTest from '../components/DynamicTest'
// import ScatterPlotTest from '../components/ScatterPlotTest'
// import TipTest from '../components/TipTest'
// import LineTest from '../components/LineTest'
// import LayoutTest from '../components/LayoutTest'
// import StackTest from '../components/StackTest'
// import StackTest2 from '../components/StackTest2'
// import PieTest from '../components/PieTest'
// import BrushTest from '../components/PieTest'
import ForceLayoutTest from '../components/ForceLayoutTest'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* <Test/> */}
        {/* <ScaleTest/> */}
        {/* <DynamicTest/> */}
        {/* <ScatterPlotTest/> */}
        {/* <TipTest/> */}
        {/* <LineTest/> */}
        {/* <LayoutTest/> */}
        {/* <StackTest/>
        <StackTest2/> */}
        {/* <PieTest/> */}
        {/* <BrushTest/> */}
        <ForceLayoutTest/>
      </main>
    </>
  )
}
