import Head from 'next/head'
import Test from '../components/Test'
import ScaleTest from '../components/ScaleTest'
import DynamicTest from '../components/DynamicTest'
import ScatterPlotTest from '../components/ScatterPlotTest'
import TipTest from '../components/TipTest'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* <Test/> */}
        {/* <ScaleTest/> */}
        {/* <DynamicTest/> */}
        {/* <ScatterPlotTest/> */}
        <TipTest/>
      </main>
    </>
  )
}
